name: Resident ui manual push

on: workflow_dispatch

jobs:
  build-resident-ui:

    runs-on: ubuntu-latest
    env:
      NAMESPACE: ${{ secrets.dev_namespace_docker_hub }}
      SERVICE_NAME: resident-ui
      SERVICE_LOCATION: resident-ui

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install npm dependencies
        run: cd ${{ env.SERVICE_LOCATION }} && npm install --ignore-scripts

      - name: Build frontend
        run: |
          cd ${{ env.SERVICE_LOCATION }}
          npm run-script build -- --prod --base-href . --output-path=dist
          echo "Build output:"
          ls -la dist

      - name: Copy dist to root (if Dockerfile expects /dist)
        run: |
          ls -la ${{ env.SERVICE_LOCATION }}/dist
          cp -r ${{ env.SERVICE_LOCATION }}/dist ./dist

      - name: Setup branch and env
        run: |
          echo "BRANCH_NAME=$(echo ${{ github.ref }} | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_ENV
          echo "GPG_TTY=$(tty)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          cd "./${{env.SERVICE_LOCATION}}"
          docker build . --file Dockerfile --tag ${{ env.SERVICE_NAME }}

      - name: Log into Docker registry
        run: echo "${{ secrets.release_docker_hub }}" | docker login -u ${{ secrets.actor_docker_hub }} --password-stdin

      - name: Push Docker image
        run: |
          IMAGE_ID=$NAMESPACE/$SERVICE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$BRANCH_NAME
          echo "push version $VERSION"
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $SERVICE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
